GHA: Do apt-get update before adding repos
There are failures like
> 	Adding repository ppa:ubuntu-toolchain-r/test
> Error: retrieving gpg key timed out.

So add an intermediate update to avoid this.